disabled_rules:
- force_cast
- large_tuple
- trailing_whitespace

line_length:
  - 200 # warning
  - 300 # error

excluded:
- Carthage
- Pods

identifier_name:
 min_length: # only min_length
  warning: 1
  error: 1
